version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: >
      sh -c "
        echo 'Waiting for Redis...' &&
        sleep 5 &&
        echo 'Updating usage stats...' &&
        npm run update-stats || echo 'Stats update failed, continuing...' &&
        echo 'Starting development server...' &&
        npm run dev
      "

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: